SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE APPLICATION;
TRUNCATE TABLE REPORT;
TRUNCATE TABLE INTERNSHIP;
TRUNCATE TABLE COMPANY;
TRUNCATE TABLE FACULTY;
TRUNCATE TABLE STUDENT;

SET FOREIGN_KEY_CHECKS = 1;

SOURCE sample_data.sql;